# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: are_we_there_yet 1.2.0 ruby bin

Gem::Specification.new do |s|
  s.name = "are_we_there_yet".freeze
  s.version = "1.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["bin".freeze]
  s.authors = ["Andy Maleh".freeze]
  s.date = "2020-10-16"
  s.description = "Small Project Tracking Desktop App built with Glimmer".freeze
  s.email = "andy.am@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "Jars.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "app/are_we_there_yet.rb",
    "app/models/are_we_there_yet/custom_tool_tip_content_replacer.rb",
    "app/models/are_we_there_yet/gantt_chart_settings.rb",
    "app/models/are_we_there_yet/task.rb",
    "app/views/are_we_there_yet/app_view.rb",
    "app/views/are_we_there_yet/filter_form.rb",
    "app/views/are_we_there_yet/preferences_dialog.rb",
    "app/views/are_we_there_yet/splash.rb",
    "app/views/are_we_there_yet/task_form.rb",
    "app/views/are_we_there_yet/task_table.rb",
    "are-we-there-yet-logo.png",
    "are-we-there-yet-screenshot-windows.png",
    "are-we-there-yet-screenshot.png",
    "are-we-there-yet-splash.gif",
    "bin/are_we_there_yet",
    "bin/org/yaml/snakeyaml/1.26/snakeyaml-1.26.jar",
    "package/macosx/Are We There Yet.icns",
    "package/windows/Are We There Yet.ico",
    "vendor/jars/org/yaml/snakeyaml/1.26/snakeyaml-1.26.jar",
    "vendor/nebula/org.eclipse.nebula.widgets.ganttchart_1.0.0.jar",
    "vendor/org/yaml/snakeyaml/1.26/snakeyaml-1.26.jar"
  ]
  s.homepage = "http://github.com/AndyObtiva/are_we_there_yet".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.1.4".freeze
  s.summary = "Small Project Tracking Desktop App".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_runtime_dependency(%q<glimmer-dsl-swt>.freeze, ["~> 4.17.2.3"])
    s.add_runtime_dependency(%q<glimmer-cw-cdatetime-nebula>.freeze, ["~> 1.5.0.1.0"])
    s.add_runtime_dependency(%q<activerecord>.freeze, ["~> 5.2.4.3"])
    s.add_runtime_dependency(%q<activerecord-jdbcsqlite3-adapter>.freeze, ["~> 52.6"])
    s.add_development_dependency(%q<glimmer-cs-gladiator>.freeze, [">= 0"])
    s.add_development_dependency(%q<jeweler>.freeze, [">= 0"])
    s.add_development_dependency(%q<warbler>.freeze, [">= 0"])
  else
    s.add_dependency(%q<glimmer-dsl-swt>.freeze, ["~> 4.17.2.3"])
    s.add_dependency(%q<glimmer-cw-cdatetime-nebula>.freeze, ["~> 1.5.0.1.0"])
    s.add_dependency(%q<activerecord>.freeze, ["~> 5.2.4.3"])
    s.add_dependency(%q<activerecord-jdbcsqlite3-adapter>.freeze, ["~> 52.6"])
    s.add_dependency(%q<glimmer-cs-gladiator>.freeze, [">= 0"])
    s.add_dependency(%q<jeweler>.freeze, [">= 0"])
    s.add_dependency(%q<warbler>.freeze, [">= 0"])
  end
end

